version: "3.5"
services:
  postgraphile:
    image: graphile/postgraphile:latest
    ports:
      - 5000
    command:
      --connection postgres://postgres:password@postgres:5432/postgres --schema forum_example --watch

  postgres:
    image: postgres:10.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
        - ./postgresql-data/:/var/lib/postgresql/data

  wait_postgres:
    image: "waisbrot/wait"
    environment:
      TARGETS: postgres:5432
